# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0493efd65621f021dfd12a45e01bd0820c66a073d5f8bb8efdfaccdc90668e305bdc337171557eb7804d6ad3072e1892c0ba3eb5b42ffd0032da9e048e71c9eb

test:
  secret_key_base: 37895e555765388528e4728f4f5abc4d18d7cbfb72058c8c19272b1802483afbeb2f4b5bdecc8436b750d1724d4abc53ebe24f0de1a6aaeed204af333fb40971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
